<?xml version="1.0" encoding="ISO-8859-1" ?>
<Messages version="maxedit" cleanup="false">
  
  <Message id="BMXOT001E" group="otrename" key="renamenotsupported" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>Rename is not supported on this object type: {0}</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT002I" group="otrename" key="renamecomplete" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>The rename operation has completed successfully</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT003E" group="otrename" key="renameactive" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>There is already a rename operation in progress</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT004E" group="otrename" key="backuprequired" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>You must indicate that a backup has been taken before you run the rename.</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT005E" group="otrename" key="valuerequired" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>You must specify a value for New Name</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT006E" group="otrename" key="objexists" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>An record already exists with this new name: {0}</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT007E" group="otrename" key="objexistsinothersite" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>The record selected to be renamed exists with the same name in a different site or set.</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT008E" group="otrename" key="renamefailure" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>The record selected to be renamed exists with the same name in a different site or set.</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  <Message id="BMXOT009I" group="otrename" key="renamestarted" prefix="YES">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>The rename operation has started. Please click the refresh button to observe the progress of the rename operation.</MsgText>
    <Explanation></Explanation>
    <AdminResponse></AdminResponse>
    <OperatorResponse></OperatorResponse>
  </Message> 
  
</Messages>